import { C } from './constants'
import type { CSSProperties } from 'react'

export const S = {
  app: {
    minHeight: '100vh',
    background: C.bg,
    color: C.cream,
    fontFamily: "'Montserrat',sans-serif",
    fontSize: 14,
  } as CSSProperties,
  hdr: {
    background: `linear-gradient(180deg,${C.bg2} 0%,${C.bg} 100%)`,
    borderBottom: `1px solid ${C.border}`,
    padding: '0 28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 68,
    position: 'sticky',
    top: 0,
    zIndex: 100,
  } as CSSProperties,
  wrap: {
    maxWidth: 1180,
    margin: '0 auto',
    padding: '40px 24px 80px',
  } as CSSProperties,
  card: {
    background: C.bg2,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    padding: 24,
  } as CSSProperties,
  lbl: {
    fontSize: 10,
    color: C.muted,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    marginBottom: 7,
    display: 'block',
    fontWeight: 600,
  } as CSSProperties,
  inp: {
    width: '100%',
    background: C.bg3,
    border: `1px solid ${C.border2}`,
    color: C.cream,
    padding: '11px 14px',
    borderRadius: 6,
    fontSize: 13,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    colorScheme: 'dark',
  } as CSSProperties,
  badge: (col: string): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '3px 10px',
    borderRadius: 20,
    fontSize: 10,
    fontWeight: 700,
    background: `${col}20`,
    color: col,
    border: `1px solid ${col}40`,
  }),
  btnG: {
    background: `linear-gradient(135deg,${C.gold} 0%,${C.goldLt} 100%)`,
    color: C.bg,
    border: 'none',
    padding: '13px 28px',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
  } as CSSProperties,
  btnGh: {
    background: 'transparent',
    color: C.muted,
    border: `1px solid ${C.border2}`,
    padding: '10px 20px',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    fontFamily: 'inherit',
  } as CSSProperties,
  btnSm: {
    background: 'transparent',
    color: C.muted,
    border: `1px solid ${C.border2}`,
    padding: '6px 14px',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 11,
    letterSpacing: 1,
    fontFamily: 'inherit',
  } as CSSProperties,
  ttl: {
    fontFamily: "'Playfair Display',serif",
    fontSize: 28,
    fontWeight: 700,
    margin: '0 0 6px',
    color: C.cream,
  } as CSSProperties,
  sub: {
    fontSize: 13,
    color: C.muted,
    margin: '0 0 28px',
  } as CSSProperties,
  step: {
    fontSize: 10,
    color: C.gold,
    letterSpacing: 3,
    textTransform: 'uppercase',
    fontWeight: 700,
    marginBottom: 10,
  } as CSSProperties,
}
